#!/usr/bin/env bash
"""Secure HTTPS traffic
   so that no unencrypted traffic is possible
   Configure HAproxy to automatically
   redirect HTTP traffic to HTTPS.
   """

global
    log     /dev/log local0
    maxconn 2048
    user    haproxy
    group   haproxy
    tune.ssl.default-dh-param 2048

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option  redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
    option  forwardfor
    option  http-server-close

frontend www-http
    bind   0.0.0.0:80
    reqadd X-Forwarded-Proto:\ http
    default_backend www-backend
    redirect scheme https code 301 if !{ ssl_fc }

frontend www-https
    bind   0.0.0.0:443 ssl crt /etc/haproxy/certs/www.op-cit.tech.pem
    reqadd X-Forwarded-Proto:\ https
    acl    letsencrypt-acl path_beg /.well-known/acme-challenge/
    use_backend letsencrypt-backend if letsencrypt-acl
    default_backend www-backend

backend www-backend
    balance  roundrobin
    redirect scheme https if !{ ssl_fc }
    server 45608-web-01 3.83.227.134:80 check
    server 45608-web-02 18.235.255.229:80 check

backend letsencrypt-backend
    server letsencrypt 127.0.0.1:54321
