#!/usr/bin/env bash
#Fixes a web server to run nginx as the nginx user lstening to port 8080
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
